/*
 * Copyright 2023 University of Michigan EECS183
 *
 * AI.cpp
 * Project UID 28eb18c2c1ce490aada441e65559efdd
 *
 * Grace Baily, Sofia Ryan, Chris Sherbenou, Colin Gordon
 * gbaily, sofiary, csherben, cogo
 *
 * Final Project - Elevators
 */

#include "AI.h"
#include <cassert>

// This file is used only in the Reach, not the Core.
// You do not need to make any changes to this file for the Core

/*
* Requires: buildingState is a valid state representing the current building
* Modifies: Nothing
* Effects:  Returns a string that represents the decision the AI makes
*           given the current state of the building, which it reads
*           from buildingState.
*           The string should share the exact format as a
*           human player's move input.
*/
string getAIMoveString(const BuildingState& buildingState) {
    
    //if there arent any people to pickup on any floor, do a pass move
    /* how to play the game successfully:
     1) if there are more ppl to pick up on a floor but other floors have higher anger levels, prioritize picking up ppl with higher anger (7, should get there soon, 8, should get there,9 urgent
     2) if there are a lot of 7,8,9, go there first
     3) plan ahead which elevator it makes most sense to service a floor. if there are people on a floor with 7/8 anger levels and close by is a floor with 9 anger levels, send it to 9 and have the next closest elevator pickup the 7/8 anger levels
     4) Biggest thing is sending the closest elevator to pickup ppl with highest anger so it reduces the amount of time. then continue
     5) Do not have pickup every move
     6) Be conscious of the amount of ticks to do something
     
     */
    
    return "";
}


/*
* Requires: buildingState is a valid state representing the current building
*           move is a pickup move that was generated by getAIMoveString()
*           floorToPickup represents the floor the pickup move occurred.
* Modifies: Nothing
* Effects:  Returns a string representing which people indices
*           should be picked up. The string should share the exact format
*           as a human player's pickup list input.
*/
string getAIPickupList(const Move& move, const BuildingState& buildingState, 
                       const Floor& floorToPickup) {
    return "";
}
